# Generated by Django 4.2 on 2023-04-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='body',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='body',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='body',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='body',
        ),
        migrations.RemoveField(
            model_name='hamster',
            name='body',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='body',
        ),
        migrations.AddField(
            model_name='bird',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bird',
            name='typ',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cat',
            name='typ',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='typ',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fish',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fish',
            name='typ',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamster',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hamster',
            name='typ',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rabbit',
            name='age',
            field=models.PositiveIntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rabbit',
            name='typ',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
