# Generated by Django 4.2 on 2023-04-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_bird_body_remove_cat_body_remove_dog_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='Img')),
                ('typ', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
