# Generated by Django 4.2 on 2023-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sargyt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
    ]
